# Generated by Django 5.0.2 on 2024-02-19 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='billingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='city')),
                ('zipcode', models.CharField(blank=True, max_length=10, verbose_name='zipcode')),
                ('country', models.CharField(blank=True, max_length=30, verbose_name='country')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='phone')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billingAddress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Billing Addresses',
            },
        ),
    ]
